# hello new script phugoid

In [3]:
import numpy as np

In [4]:
theline=np.linspace(4,23,num=43)

In [5]:
theline[6]

6.714285714285714

In [6]:
theline[0]

4.0

In [7]:
theline[5]

6.261904761904762

In [9]:
ones_array=np.ones((5,17))

In [10]:
print(ones_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
zeros_array=np.zeros(ones_array.shape)

In [13]:
print(zeros_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
p=7

In [15]:
r=np.array([11.2,4.7,6.6])

In [16]:
s=(np.sin(p/r))**3

In [17]:
s

array([0.20030151, 0.99009101, 0.66454238])